// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_json`, `to_json`

Future<String> theatreInit({required String configJson}) =>
    RustLib.instance.api.crateApiTheatreInit(configJson: configJson);

Future<void> theatreShutdown() =>
    RustLib.instance.api.crateApiTheatreShutdown();

Future<String> theatreSearch({
  required String query,
  List<String>? sourceFilter,
}) => RustLib.instance.api.crateApiTheatreSearch(
  query: query,
  sourceFilter: sourceFilter,
);

Future<String> theatreGetDetails({required String contentJson}) =>
    RustLib.instance.api.crateApiTheatreGetDetails(contentJson: contentJson);

Future<String> theatreListSources() =>
    RustLib.instance.api.crateApiTheatreListSources();

Future<String> theatreResolve({
  required String contentJson,
  String? variant,
  required bool forceRefresh,
}) => RustLib.instance.api.crateApiTheatreResolve(
  contentJson: contentJson,
  variant: variant,
  forceRefresh: forceRefresh,
);

Future<String> theatreEnqueueDownload({
  required String contentJson,
  required String streamJson,
  required String title,
  String? variant,
}) => RustLib.instance.api.crateApiTheatreEnqueueDownload(
  contentJson: contentJson,
  streamJson: streamJson,
  title: title,
  variant: variant,
);

Future<String> theatreListDownloads() =>
    RustLib.instance.api.crateApiTheatreListDownloads();

Future<void> theatrePauseDownload({required String id}) =>
    RustLib.instance.api.crateApiTheatrePauseDownload(id: id);

Future<void> theatreCancelDownload({required String id}) =>
    RustLib.instance.api.crateApiTheatreCancelDownload(id: id);

Future<void> theatreResumeDownload({required String id}) =>
    RustLib.instance.api.crateApiTheatreResumeDownload(id: id);

Future<void> theatreRecordPlayback({required String entryJson}) =>
    RustLib.instance.api.crateApiTheatreRecordPlayback(entryJson: entryJson);

Future<String> theatreContinueWatching({required int limit}) =>
    RustLib.instance.api.crateApiTheatreContinueWatching(limit: limit);

Future<String> theatreAllHistory({required int limit, required int offset}) =>
    RustLib.instance.api.crateApiTheatreAllHistory(
      limit: limit,
      offset: offset,
    );

Future<void> theatreDeleteHistory({required String id}) =>
    RustLib.instance.api.crateApiTheatreDeleteHistory(id: id);

Future<String> theatreListLocations() =>
    RustLib.instance.api.crateApiTheatreListLocations();

Future<String> theatreAddLocation({
  required String path,
  String? label,
  required bool isSaf,
}) => RustLib.instance.api.crateApiTheatreAddLocation(
  path: path,
  label: label,
  isSaf: isSaf,
);

Future<void> theatreRemoveLocation({required String id}) =>
    RustLib.instance.api.crateApiTheatreRemoveLocation(id: id);

Future<String> theatreBrowseFolder({required String path}) =>
    RustLib.instance.api.crateApiTheatreBrowseFolder(path: path);

Future<String?> theatreGetSetting({required String key}) =>
    RustLib.instance.api.crateApiTheatreGetSetting(key: key);

Future<void> theatreSetSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiTheatreSetSetting(key: key, value: value);
