// Theatre API types — mirrors data-contract.md §1.
// Actual FFI bridge is generated by flutter_rust_bridge; this file
// provides the Dart-side type system for the generated code.

import 'package:freezed_annotation/freezed_annotation.dart';
part 'types.freezed.dart';
part 'types.g.dart';

@freezed
abstract class InitConfig with _$InitConfig {
  const factory InitConfig({
    required String dataDir,
    required String appVersion,
    @Default(true) bool proxyEnabled,
  }) = _InitConfig;
  factory InitConfig.fromJson(Map<String, dynamic> j) => _$InitConfigFromJson(j);
}

@freezed
abstract class InitResult with _$InitResult {
  const factory InitResult({
    required String dbPath,
    int? proxyPort,
    required String coreVersion,
    required String contractVersion,
  }) = _InitResult;
  factory InitResult.fromJson(Map<String, dynamic> j) => _$InitResultFromJson(j);
}

enum ContentKind { movie, series, episode }

@freezed
abstract class ContentRef with _$ContentRef {
  const factory ContentRef({
    required String source,
    required String contentId,
    required ContentKind kind,
  }) = _ContentRef;
  factory ContentRef.fromJson(Map<String, dynamic> j) => _$ContentRefFromJson(j);
}

@freezed
abstract class SearchResult with _$SearchResult {
  const factory SearchResult({
    required ContentRef content,
    required String title,
    int? year,
    String? posterUrl,
    @Default([]) List<String> qualityBadges,
  }) = _SearchResult;
  factory SearchResult.fromJson(Map<String, dynamic> j) => _$SearchResultFromJson(j);
}

@freezed
abstract class SearchPage with _$SearchPage {
  const factory SearchPage({
    required List<SearchResult> results,
    @Default(false) bool hasMore,
    @Default(false) bool partial,
  }) = _SearchPage;
  factory SearchPage.fromJson(Map<String, dynamic> j) => _$SearchPageFromJson(j);
}

@freezed
abstract class Episode with _$Episode {
  const factory Episode({
    required ContentRef content,
    required int season,
    required int episode,
    required String title,
    String? description,
    String? thumbnailUrl,
    int? durationSeconds,
  }) = _Episode;
  factory Episode.fromJson(Map<String, dynamic> j) => _$EpisodeFromJson(j);
}

@freezed
abstract class Details with _$Details {
  const factory Details({
    required ContentRef content,
    required String title,
    String? description,
    int? year,
    String? posterUrl,
    String? backdropUrl,
    String? rating,
    List<String>? genres,
    int? durationSeconds,
    @Default([]) List<Episode> episodes,
  }) = _Details;
  factory Details.fromJson(Map<String, dynamic> j) => _$DetailsFromJson(j);
}

enum StreamKind { direct, hls }

@freezed
abstract class Variant with _$Variant {
  const factory Variant({
    required String id,
    required String label,
    int? width,
    int? height,
    int? bitrateKbps,
  }) = _Variant;
  factory Variant.fromJson(Map<String, dynamic> j) => _$VariantFromJson(j);
}

@freezed
abstract class ResolvedStream with _$ResolvedStream {
  const factory ResolvedStream({
    required String url,
    @Default({}) Map<String, String> headers,
    required StreamKind kind,
    @Default([]) List<Variant> variants,
    String? selectedVariant,
    String? filenameHint,
    int? sizeBytes,
  }) = _ResolvedStream;
  factory ResolvedStream.fromJson(Map<String, dynamic> j) => _$ResolvedStreamFromJson(j);
}

enum SourceStatus { healthy, degraded }

@freezed
abstract class SourceInfo with _$SourceInfo {
  const factory SourceInfo({
    required String id,
    required String name,
    required bool enabled,
    @Default(SourceStatus.healthy) SourceStatus status,
  }) = _SourceInfo;
  factory SourceInfo.fromJson(Map<String, dynamic> j) => _$SourceInfoFromJson(j);
}

enum JobStatus { queued, preparing, running, paused, failed, done, cancelled }
enum JobKind   { direct, hls }

@freezed
abstract class DownloadJob with _$DownloadJob {
  const factory DownloadJob({
    required String id,
    required String title,
    String? variant,
    required JobKind kind,
    required String destPath,
    required JobStatus status,
    @Default(0) int bytesDone,
    int? totalBytes,
    @Default(0) int segmentsDone,
    int? totalSegments,
    String? errorMsg,
    required int createdAt,
  }) = _DownloadJob;
  factory DownloadJob.fromJson(Map<String, dynamic> j) => _$DownloadJobFromJson(j);
}

@freezed
abstract class HistoryEntry with _$HistoryEntry {
  const factory HistoryEntry({
    required String id,
    String? sourceId,
    String? contentId,
    String? localPath,
    required String title,
    String? posterUrl,
    String? variant,
    @Default(0) int positionSeconds,
    int? durationSeconds,
    required int lastWatched,
    @Default(0) int playCount,
    @Default(false) bool completed,
  }) = _HistoryEntry;
  factory HistoryEntry.fromJson(Map<String, dynamic> j) => _$HistoryEntryFromJson(j);
}

@freezed
abstract class LibraryLocation with _$LibraryLocation {
  const factory LibraryLocation({
    required String id,
    required String path,
    required String kind,
    String? label,
    required int addedAt,
  }) = _LibraryLocation;
  factory LibraryLocation.fromJson(Map<String, dynamic> j) => _$LibraryLocationFromJson(j);
}

@freezed
abstract class MediaEntry with _$MediaEntry {
  const factory MediaEntry({
    required String name,
    required String path,
    required bool isDir,
    int? sizeBytes,
    @Default(true) bool exists,
  }) = _MediaEntry;
  factory MediaEntry.fromJson(Map<String, dynamic> j) => _$MediaEntryFromJson(j);
}
